server:
  port: 8021

spring:
  application:
    name: konfig-authentication
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lite_config?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: "0412"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  cloud:
    zookeeper:
      connect-string: 10.255.254.152:2181
  redis:
    database: 0 # 0号数据库存用户信息
    host: 10.255.254.152
    port: 6379
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000
    password: 123456

mybatis:
  #  定义实体类位置
  type-aliases-package: org.zhangxujie.konfig.model

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: lite-config-secret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)一天
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  token: Authorization

